log:
  level: debug

# mysql相关配
mysql:
  address: '192.168.56.11:3306'
  username: root
  password: '123456'
  dbname: 'fleetpilot'
  timeout: 10
  multiStatements: true

# JWT相关
jwt:
  accessSecret: 12345
  refreshSecret: 12345
  accessExp: 15m
  refreshExp: 168h
  issuedAt: 'abcd'

# redis配置
redis:
  address: '192.168.56.11:6379'
  password: ''
  db: 0
